import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-search',
  standalone: true, // <-- Add this line
  imports: [CommonModule],
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss'], // <-- Correct property name
})
export class SearchComponent {
  buses = [
    {
      primo: true,
      operator: 'Cauvery Travels',
      type: 'Non A/C Seater / Sleeper (2+1)',
      rating: 4.5,
      ratingCount: 652,
      departure: '23:30',
      arrival: '07:17',
      duration: '7h 47m',
      seats: 10,
      singleSeats: 6,
      price: 750,
    },
    {
      primo: false,
      operator: 'Sugama Tourist',
      type: 'NON A/C Sleeper (2+1)',
      rating: 4.5,
      ratingCount: 358,
      departure: '23:07',
      arrival: '06:01',
      duration: '6h 54m',
      seats: 18,
      singleSeats: 1,
      price: 750,
    },
    {
      primo: true,
      operator: 'Bharathi Travels',
      type: 'A/C Sleeper (2+1)',
      rating: 4.4,
      ratingCount: 11,
      departure: '22:40',
      arrival: '04:39',
      duration: '5h 59m',
      seats: 19,
      singleSeats: 5,
      price: 740,
    },
    {
      primo: false,
      operator: 'SRS Travels',
      type: 'A/C Seater / Sleeper (2+1)',
      rating: 4.2,
      ratingCount: 210,
      departure: '21:30',
      arrival: '05:00',
      duration: '7h 30m',
      seats: 15,
      singleSeats: 4,
      price: 800,
    },
    {
      primo: true,
      operator: 'VRL Travels',
      type: 'A/C Sleeper (2+1)',
      rating: 4.7,
      ratingCount: 500,
      departure: '20:45',
      arrival: '04:15',
      duration: '7h 30m',
      seats: 12,
      singleSeats: 3,
      price: 950,
    },
    {
      primo: false,
      operator: 'Rajesh Travels',
      type: 'Non A/C Sleeper (2+1)',
      rating: 4.0,
      ratingCount: 120,
      departure: '19:30',
      arrival: '03:30',
      duration: '8h 0m',
      seats: 20,
      singleSeats: 7,
      price: 700,
    },
    {
      primo: false,
      operator: 'Orange Tours',
      type: 'A/C Seater (2+2)',
      rating: 4.3,
      ratingCount: 340,
      departure: '22:00',
      arrival: '06:00',
      duration: '8h 0m',
      seats: 14,
      singleSeats: 2,
      price: 820,
    },
    {
      primo: true,
      operator: 'KPN Travels',
      type: 'A/C Sleeper (2+1)',
      rating: 4.6,
      ratingCount: 410,
      departure: '21:15',
      arrival: '05:45',
      duration: '8h 30m',
      seats: 16,
      singleSeats: 6,
      price: 980,
    },
    {
      primo: false,
      operator: 'GreenLine Travels',
      type: 'Non A/C Seater (2+2)',
      rating: 3.9,
      ratingCount: 90,
      departure: '20:00',
      arrival: '03:30',
      duration: '7h 30m',
      seats: 22,
      singleSeats: 8,
      price: 650,
    },
    {
      primo: false,
      operator: 'Seabird Tourists',
      type: 'A/C Sleeper (2+1)',
      rating: 4.1,
      ratingCount: 200,
      departure: '23:00',
      arrival: '06:30',
      duration: '7h 30m',
      seats: 13,
      singleSeats: 4,
      price: 900,
    },
    {
      primo: true,
      operator: 'Paulo Travels',
      type: 'A/C Seater / Sleeper (2+1)',
      rating: 4.8,
      ratingCount: 520,
      departure: '21:50',
      arrival: '05:20',
      duration: '7h 30m',
      seats: 11,
      singleSeats: 2,
      price: 990,
    },
    {
      primo: false,
      operator: 'VRL Express',
      type: 'Non A/C Sleeper (2+1)',
      rating: 4.0,
      ratingCount: 180,
      departure: '22:30',
      arrival: '06:00',
      duration: '7h 30m',
      seats: 17,
      singleSeats: 5,
      price: 770,
    },
    {
      primo: false,
      operator: 'Durgamba Motors',
      type: 'A/C Seater (2+2)',
      rating: 3.8,
      ratingCount: 75,
      departure: '20:30',
      arrival: '04:00',
      duration: '7h 30m',
      seats: 21,
      singleSeats: 7,
      price: 720,
    },
    {
      primo: true,
      operator: 'SRS Deluxe',
      type: 'A/C Sleeper (2+1)',
      rating: 4.9,
      ratingCount: 600,
      departure: '23:15',
      arrival: '06:45',
      duration: '7h 30m',
      seats: 9,
      singleSeats: 3,
      price: 1050,
    },
    {
      primo: false,
      operator: 'Kallada Travels',
      type: 'Non A/C Seater / Sleeper (2+1)',
      rating: 4.2,
      ratingCount: 230,
      departure: '21:00',
      arrival: '04:30',
      duration: '7h 30m',
      seats: 18,
      singleSeats: 6,
      price: 780,
    },
    {
      primo: false,
      operator: 'Sharma Transports',
      type: 'A/C Sleeper (2+1)',
      rating: 4.3,
      ratingCount: 310,
      departure: '22:20',
      arrival: '05:50',
      duration: '7h 30m',
      seats: 15,
      singleSeats: 5,
      price: 860,
    },
    {
      primo: true,
      operator: 'National Travels',
      type: 'A/C Seater (2+2)',
      rating: 4.7,
      ratingCount: 480,
      departure: '20:10',
      arrival: '03:40',
      duration: '7h 30m',
      seats: 20,
      singleSeats: 8,
      price: 930,
    },
    {
      primo: false,
      operator: 'SRS Classic',
      type: 'Non A/C Sleeper (2+1)',
      rating: 4.1,
      ratingCount: 160,
      departure: '21:40',
      arrival: '05:10',
      duration: '7h 30m',
      seats: 19,
      singleSeats: 7,
      price: 800,
    },
    {
      primo: false,
      operator: 'VRL Comfort',
      type: 'A/C Sleeper (2+1)',
      rating: 4.0,
      ratingCount: 140,
      departure: '22:10',
      arrival: '05:40',
      duration: '7h 30m',
      seats: 14,
      singleSeats: 4,
      price: 870,
    },
    {
      primo: true,
      operator: 'Paulo Premium',
      type: 'A/C Seater / Sleeper (2+1)',
      rating: 4.9,
      ratingCount: 700,
      departure: '23:20',
      arrival: '06:50',
      duration: '7h 30m',
      seats: 8,
      singleSeats: 2,
      price: 1100,
    },
  ];
}
