import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-search',
  standalone: true, // <-- Add this line
  imports: [CommonModule, FormsModule],
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss'], // <-- Correct property name
})
export class SearchComponent {
  fromLocation: string = '';
  destLocation: string = '';
  searchFrom: string = '';
  searchTo: string = '';
  buses = [
    {
      primo: true,
      operator: 'Cauvery Travels',
      type: 'Non A/C Seater / Sleeper (2+1)',
      rating: 4.5,
      ratingCount: 652,
      departure: '23:30',
      arrival: '07:17',
      duration: '7h 47m',
      seats: 10,
      singleSeats: 6,
      price: 750,
      departureLocation: 'Bangalore',
      destinationLocation: 'Chennai',
    },
    {
      primo: false,
      operator: 'Sugama Tourist',
      type: 'NON A/C Sleeper (2+1)',
      rating: 4.5,
      ratingCount: 358,
      departure: '23:07',
      arrival: '06:01',
      duration: '6h 54m',
      seats: 18,
      singleSeats: 1,
      price: 750,
      departureLocation: 'Mumbai',
      destinationLocation: 'Pune',
    },
    {
      primo: true,
      operator: 'Bharathi Travels',
      type: 'A/C Sleeper (2+1)',
      rating: 4.4,
      ratingCount: 11,
      departure: '22:40',
      arrival: '04:39',
      duration: '5h 59m',
      seats: 19,
      singleSeats: 5,
      price: 740,
      departureLocation: 'Delhi',
      destinationLocation: 'Jaipur',
    },
    {
      primo: false,
      operator: 'SRS Travels',
      type: 'A/C Seater / Sleeper (2+1)',
      rating: 4.2,
      ratingCount: 210,
      departure: '21:30',
      arrival: '05:00',
      duration: '7h 30m',
      seats: 15,
      singleSeats: 4,
      price: 800,
      departureLocation: 'Hyderabad',
      destinationLocation: 'Vizag',
    },
    {
      primo: true,
      operator: 'VRL Travels',
      type: 'A/C Sleeper (2+1)',
      rating: 4.7,
      ratingCount: 500,
      departure: '20:45',
      arrival: '04:15',
      duration: '7h 30m',
      seats: 12,
      singleSeats: 3,
      price: 950,
      departureLocation: 'Kolkata',
      destinationLocation: 'Durgapur',
    },
    {
      primo: false,
      operator: 'Rajesh Travels',
      type: 'Non A/C Sleeper (2+1)',
      rating: 4.0,
      ratingCount: 120,
      departure: '19:30',
      arrival: '03:30',
      duration: '8h 0m',
      seats: 20,
      singleSeats: 7,
      price: 700,
      departureLocation: 'Ahmedabad',
      destinationLocation: 'Surat',
    },
    {
      primo: false,
      operator: 'Orange Tours',
      type: 'A/C Seater (2+2)',
      rating: 4.3,
      ratingCount: 340,
      departure: '22:00',
      arrival: '06:00',
      duration: '8h 0m',
      seats: 14,
      singleSeats: 2,
      price: 820,
      departureLocation: 'Lucknow',
      destinationLocation: 'Kanpur',
    },
    {
      primo: true,
      operator: 'KPN Travels',
      type: 'A/C Sleeper (2+1)',
      rating: 4.6,
      ratingCount: 410,
      departure: '21:15',
      arrival: '05:45',
      duration: '8h 30m',
      seats: 16,
      singleSeats: 6,
      price: 980,
      departureLocation: 'Chandigarh',
      destinationLocation: 'Amritsar',
    },
    {
      primo: false,
      operator: 'GreenLine Travels',
      type: 'Non A/C Seater (2+2)',
      rating: 3.9,
      ratingCount: 90,
      departure: '20:00',
      arrival: '03:30',
      duration: '7h 30m',
      seats: 22,
      singleSeats: 8,
      price: 650,
      departureLocation: 'Bhopal',
      destinationLocation: 'Indore',
    },
    {
      primo: false,
      operator: 'Seabird Tourists',
      type: 'A/C Sleeper (2+1)',
      rating: 4.1,
      ratingCount: 200,
      departure: '23:00',
      arrival: '06:30',
      duration: '7h 30m',
      seats: 13,
      singleSeats: 4,
      price: 900,
      departureLocation: 'Ranchi',
      destinationLocation: 'Jamshedpur',
    },
    {
      primo: true,
      operator: 'Paulo Travels',
      type: 'A/C Seater / Sleeper (2+1)',
      rating: 4.8,
      ratingCount: 520,
      departure: '21:50',
      arrival: '05:20',
      duration: '7h 30m',
      seats: 11,
      singleSeats: 2,
      price: 990,
      departureLocation: 'Patna',
      destinationLocation: 'Gaya',
    },
    {
      primo: false,
      operator: 'VRL Express',
      type: 'Non A/C Sleeper (2+1)',
      rating: 4.0,
      ratingCount: 180,
      departure: '22:30',
      arrival: '06:00',
      duration: '7h 30m',
      seats: 17,
      singleSeats: 5,
      price: 770,
      departureLocation: 'Guwahati',
      destinationLocation: 'Shillong',
    },
    {
      primo: false,
      operator: 'Durgamba Motors',
      type: 'A/C Seater (2+2)',
      rating: 3.8,
      ratingCount: 75,
      departure: '20:30',
      arrival: '04:00',
      duration: '7h 30m',
      seats: 21,
      singleSeats: 7,
      price: 720,
      departureLocation: 'Nagpur',
      destinationLocation: 'Nashik',
    },
    {
      primo: true,
      operator: 'SRS Deluxe',
      type: 'A/C Sleeper (2+1)',
      rating: 4.9,
      ratingCount: 600,
      departure: '23:15',
      arrival: '06:45',
      duration: '7h 30m',
      seats: 9,
      singleSeats: 3,
      price: 1050,
      departureLocation: 'Thiruvananthapuram',
      destinationLocation: 'Kochi',
    },
    {
      primo: false,
      operator: 'Kallada Travels',
      type: 'Non A/C Seater / Sleeper (2+1)',
      rating: 4.2,
      ratingCount: 230,
      departure: '21:00',
      arrival: '04:30',
      duration: '7h 30m',
      seats: 18,
      singleSeats: 6,
      price: 780,
      departureLocation: 'Mangalore',
      destinationLocation: 'Udupi',
    },
    {
      primo: false,
      operator: 'Sharma Transports',
      type: 'A/C Sleeper (2+1)',
      rating: 4.3,
      ratingCount: 310,
      departure: '22:20',
      arrival: '05:50',
      duration: '7h 30m',
      seats: 15,
      singleSeats: 5,
      price: 860,
      departureLocation: 'Varanasi',
      destinationLocation: 'Allahabad',
    },
    {
      primo: true,
      operator: 'National Travels',
      type: 'A/C Seater (2+2)',
      rating: 4.7,
      ratingCount: 480,
      departure: '20:10',
      arrival: '03:40',
      duration: '7h 30m',
      seats: 20,
      singleSeats: 8,
      price: 930,
      departureLocation: 'Coimbatore',
      destinationLocation: 'Madurai',
    },
    {
      primo: false,
      operator: 'SRS Classic',
      type: 'Non A/C Sleeper (2+1)',
      rating: 4.1,
      ratingCount: 160,
      departure: '21:40',
      arrival: '05:10',
      duration: '7h 30m',
      seats: 19,
      singleSeats: 7,
      price: 800,
      departureLocation: 'Jodhpur',
      destinationLocation: 'Udaipur',
    },
    {
      primo: false,
      operator: 'VRL Comfort',
      type: 'A/C Sleeper (2+1)',
      rating: 4.0,
      ratingCount: 140,
      departure: '22:10',
      arrival: '05:40',
      duration: '7h 30m',
      seats: 14,
      singleSeats: 4,
      price: 870,
      departureLocation: 'Raipur',
      destinationLocation: 'Bilaspur',
    },
    {
      primo: true,
      operator: 'Paulo Premium',
      type: 'A/C Seater / Sleeper (2+1)',
      rating: 4.9,
      ratingCount: 700,
      departure: '23:20',
      arrival: '06:50',
      duration: '7h 30m',
      seats: 8,
      singleSeats: 2,
      price: 1100,
      departureLocation: 'Agra',
      destinationLocation: 'Mathura',
    },
  ];

  get filteredBuses() {
    return this.buses.filter((bus) => {
      const fromMatch =
        !this.searchFrom.trim() ||
        bus.departureLocation
          .toLowerCase()
          .includes(this.searchFrom.toLowerCase());
      const toMatch =
        !this.searchTo.trim() ||
        bus.destinationLocation
          .toLowerCase()
          .includes(this.searchTo.toLowerCase());
      return fromMatch && toMatch;
    });
  }

  onSearch() {
    this.searchFrom = this.fromLocation;
    this.searchTo = this.destLocation;
  }
}
